config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: [:index, :new, :create] do 
    resources :expenses, only: [:index, :new, :create]
  end
  # resources :category_expenses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "splash_screen#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses
  has_many :expenses, through: :category_expenses

  validates :name, presence: true
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :category_expenses
  has_many :categories, through: :category_expenses

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :expenses

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(_scope)
    root_path
  end

  def after_sign_in_path_for(_scope)
    categories_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = Category.where(user: current_user)
    @expenses = Expense.where(user: current_user)
    @category_expenses = CategoryExpense.all
  end

  def new
    @category = Category.new
  end

  def create
    @new_category = Category.new(category_params)
    @new_category.user_id = current_user.id
    if @new_category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  def index
    @expenses = CategoryExpense.includes(:expense).where(category_id: params[:category_id])
    @total_amount = @expenses.map { |exp| exp.expense.amount }.sum
    @category = params[:category_id]
  end

  def new
    @expense = Expense.new
  end

  def create
    @new_expense = Expense.new(expense_params)
    @new_expense.user_id = current_user.id

    @category = Category.where(user_id: current_user.id)
    @new_category_expense = CategoryExpense.new
    @new_category_expense.category_id = params[:category_id].to_i

    return unless @new_expense.save

    @new_category_expense.expense_id = @new_expense.id
    if @new_category_expense.save
      redirect_to category_expenses_path(params[:category_id])
    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_expenses_helper.rb
module CategoryExpensesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<%= render partial: "partials/login_sign_up", locals: {title: "CATEGORIES", no_auth: true}%>
<div class="categories flex_column">
    <% @categories.each do |cat|%>
        <%total_amount = 0%>

        <% @category_expenses.each do |ce|%>
            <%if ce.category_id == cat.id%>
                <% total_amount += ce.expense.amount%>
            <% end %>
        <% end %>

        <div class="cat_container center_horizontal flex">
            <div class="cat_details_main flex">
                <div class="cat_details_image flex">
                    <img src="<%= cat.icon %>">
                </div>
                <div class="cat_details_secondary flex_column">
                    <%= link_to cat.name, category_expenses_path(cat.id)%>
                    <%= cat.created_at.strftime("%B %d %Y") %>

                </div>
            </div>
            <div class="cat_amount flex">
                <strong>$ <%= total_amount%></strong>
            </div>
        </div>


    <% end %>
</div>
<button type="button" class="add_new_btn">
    <%= link_to "Add new Category", new_category_path, class: "add_new_button_inner general_text" %>
</button>

app/views/categories/new.html.erb
<%= render partial: "partials/login_sign_up", locals: {title: "NEW CATEGORY", no_auth: true}%>

<%= form_with model: @category, url: categories_path, method: :post do |f| %>
  <div class="flex_column fill_container login_form_container">

    <div class="login_field">
      <%= f.text_field :name, placeholder: "Category name", class: "general_text" %>
    </div>
    <hr/>

    <div class="login_field">
      <%= f.text_field :icon,  placeholder: "Category icon", class: "general_text" %>
    </div>
  </div>

  <button type="button" class="add_new_btn">
    <%= f.submit "SAVE", class: "add_new_button_inner general_text submit_new_btn"  %>
  </button>
<% end %>

app/views/expenses/index.html.erb
<%= render partial: "partials/login_sign_up", locals: {title: "TRANSACTIONS", no_auth: true}%>

<div class="total_expenses flex general_text">
    <span>Total amount spent in this category:</span> <span>$<%= @total_amount %></span>
</div>

<div class="expenses_container flex_column">
    <% @expenses.each do |exp|%>
        
        <div class="expense_container flex center_horizontal general_text">
            <div class="expense_name"> 
                <div class="expense_name"><%= exp.expense.name%></div>
                <div class="expense_name">Created on: <em><%= exp.expense.created_at.strftime("%B %d %Y") %></em></div>
            </div>
            <span class="expense_amount">$<%= exp.expense.amount%></span>
        </div>
    <% end %>
</div>

<button type="button" class="add_new_btn">
    <%= link_to "Add new transaction", new_category_expense_path(@category), class: "add_new_button_inner general_text" %>
</button>

app/views/expenses/new.html.erb
<%= render partial: "partials/login_sign_up", locals: {title: "NEW TRANSACTION", no_auth: true}%>

<%= form_with model: @expense, url: category_expenses_path, method: :post do |f| %>
  <div class="flex_column fill_container login_form_container">
    <div class="login_field">
      <%= f.text_field :name, placeholder: "Transaction name", class: "general_text" %>
    </div>
    <hr />
    <div class="login_field">
      <%= f.number_field :amount, placeholder: "Transaction amount", class: "general_text"  %>
    </div>
  </div>

  <button type="button" class="add_new_btn">
    <%= f.submit "SAVE", class: "add_new_button_inner general_text submit_new_btn"  %>
  </button>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpendRightBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpendRightBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
    <header>
      <nav>
        <ul class="li-login">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Categories", categories_path %></li>
          <% if user_signed_in? %>
            <li></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path, class:"log-btn" %></li>
          <% end %>
        </ul>
      </nav>
    </header>

app/views/partials/_login_sign_up.html.erb
<div class="login_sign_up_header flex">
    <div>
        <% if title == "TRANSACTIONS"%>
            <%= link_to "BACK", categories_path, class: "back_button general_text" %>
        <% elsif title == "CATEGORIES"%>
            <%= link_to "BACK", root_path, class: "back_button general_text" %>
        <% else %>
            <%= link_to "BACK", :back, class: "back_button general_text" %>
        <% end %>
    </div>

    <div class="headline header_title">
        <%= title%>    
    </div>

    <% if no_auth%>
        <div> <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, class:"log_btn general_text" %></div>
    
    <% else %>

        <div>
            <%if login%>
                <div class="form_action">
                    <%= form.submit "LOGIN" %>
                </div>
            <%else%>
                <div class="form_action">
                    <%= form.submit "SIGN UP" %>
                </div>
            <%end%>

        </div>

    <% end %>



</div>

app/views/splash_screen/index.html.erb
<div class="flex_column splash">
    
    <h1 class="flex_column headline">Spend Right</h1>

    <div class="splash_buttons flex_column">

        <% unless user_signed_in? %>
            
            <button type="button" class="log_in_button center_horizontal">
                <%= link_to "LOG IN", user_session_path, class: "log_in_link fill_container" %>
            </button>
            
            <%= link_to "SIGN UP", new_user_registration_path, class: "sign_up_link center_horizontal"%>

        <% else %>
            <%= link_to "TRANSACTION CATEGORIES", categories_path, class: "center_horizontal home_to_transactions"%>

        <% end %>
        
    </div>
</div>